---
title: Zac Heisey // Social Impact Design Consultant
description: Zac Heisey is an interaction design consultant helping purpose-driven organizations create better products, services, and experiences.
email: zheisey@gmail.com
url: https://www.zac-heisey.com # the base hostname & protocol for your site, e.g. http://example.com

collections:
  posts:
    title: Posts
    output: true
  lessons:
    title: Lessons
    output: true
    permalink: "/web-dev-101/:path/"
  projects:
    title: Projects
    output: true
    permalink: "/work/:path"

defaults: # see admin/config.yml file for Netlify CMS front matter defaults
- scope:
    path: ''
    type: posts
  values:
    categories: blog
    permalink: "/:categories/:title"
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: default

permalink: pretty

include:
- _redirects

plugins:
- jekyll-sitemap

#Build Settings
markdown: kramdown

kramdown:
  auto_ids: false
